config/routes.rb
Vizibid::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :forms
  resources :comments
  resources :form_requests
  resources :form_ratings
  resources :user_details
  resources :user_notifications
  resources :user_feedbacks, only: [:new, :create]
  resources :inappropriate_documents, only: [:create]
  resources :inappropriate_requests, only: [:create]
  resources :password_resets

  root :to => 'pages#home'

  match 'password_resets/new' => 'password_resets#new', :via => :get
  match '/press' => 'pages#press'
  match '/faq' => 'pages#faq'
  match '/learn_more/' => 'pages#learnmore', :as => :learn_more_base
  match '/learn_more/:path' => 'pages#learnmore', :as => :learn_more
  match '/support' => 'pages#support'
  match '/privacy_policy' => 'pages#privacy_policy'
  match '/terms_of_use' => 'pages#terms_of_use'
  match '/why' => 'pages#why'
  match '/requestcenter' => 'pages#requestcenter'
  match '/history' => 'pages#history'
  match '/share' => 'pages#share'
  match '/feedback' => 'pages#feedback'
  match '/signup' => 'users#new'
  match '/settings' => redirect('/settings/account')
  match '/settings/:path' => 'pages#settings', :as => :settings
  match '/download' =>'forms#download', :via => :get
  match '/signin' => 'sessions#new'
  match '/signout' => 'sessions#destroy', :via => :delete
  match '/completerequest/:id' => 'form_requests#completerequest', :as => :completerequest
  match '/completerequestfrompage/:id' => 'form_requests#completerequestfrompage', :as => :completerequestfrompage
  match '/form_requests/edit/:id/:comment' => 'form_requests#edit', :as => :requestcomment
  match '/deleteresponse/:id' => 'form_requests#destroy_response', :as => :deleteresponse
  match '/verify/:id' => 'users#verify', :as => :verify
  match '/deleteforumcomment/:id' => 'forum_comments#delete_forum_comment', :as => :deleteforumcomment
  match '/practicearea' => 'user_practice_areas#update', :via => :post, :as => :practicearea
  match '/follow/:id' => 'form_follows#update', :via => :get, :as => :followform
  match '/unfollow/:id' => 'form_follows#unfollow', :via => :get, :as => :unfollowform
  match '/approveresponse/:id' => 'form_requests#approveresponse', :via => :get, :as => :approveresponse
  match '/share/:id' => 'shared_forms#create', :via => :post, :as => :share

  match ':name' => 'users#show', :as => :usershow










end

app/views/pages/requestcenter_partials/_requestcenter_all_requests.html.erb
<%= form_tag requestcenter_path, :method => 'get' do %>
	<%= text_field_tag :search, params[:search], :placeholder => "Search Requests", :class => "searchbox"%>
	<%= submit_tag "Search", :class => "btn btn-info" %>
<% end %>

<% if @permitted_user %>
	<%= link_to "View My Requests", :controller => "pages", :action => "requestcenter", :scope => "me" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<% else %>
	<%= render 'layouts/noaccess_modal', :type =>"myreqs" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<% end %>

<% if @permitted_user %>
	<%= link_to "Request a Document", new_form_request_path %>
<% else %>
	<%= render 'layouts/noaccess_modal', :type =>"request" %>
<% end %>

<% @i = 1 %>
<br/><br/>
<% if @search != nil %>
	<h3><%= pluralize(@total_requests, 'result') %>:</h3><br/>
<% else %>
	<h3><%= pluralize(@total_requests, 'open request')%></h3><br/>
<% end %>

<% @form_requests.each do |f| %>
  <% if f.fufilled != true %>
	  <tr>
	    <td><%= render 'form_requests/form_request_summary', :f => f, :showstatus => 'false' %></td>
	  </tr>
	  <% @i += 1 %>
	  <% if @i < @form_requests.count+1 %>
	  	  <hr/>
	  <% end %>
  <% end %>
<% end %>

<%= will_paginate(@form_requests) %>

app/views/pages/requestcenter_partials/_requestcenter_my_requests.html.erb
<h3>You have <%= @form_requests.count %> requests</h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<br/>
<%= link_to "Back to Request Center", requestcenter_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<%= link_to "Request a Document", new_form_request_path %>
<hr/>
<% @i = 1 %>
<% @form_requests.each do |f| %>
  <tr>
    <td><%= render 'form_requests/form_request_summary', :f => f, :i => @i, :showstatus => 'true' %></td>
  </tr>
  <% @i += 1 %>
  <% if @i < @form_requests.count+1 %>
  	  <hr/>
  <% end %>
<% end %>

<%= will_paginate(@form_requests) %>