config/routes.rb
Vizibid::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :forms
  resources :comments
  resources :form_requests
  resources :form_ratings
  resources :user_details
  resources :user_notifications
  resources :user_feedbacks, only: [:new, :create]
  resources :inappropriate_documents, only: [:create]
  resources :inappropriate_requests, only: [:create]
  resources :password_resets

  root :to => 'pages#home'

  match 'password_resets/new' => 'password_resets#new', :via => :get
  match '/press' => 'pages#press'
  match '/faq' => 'pages#faq'
  match '/learn_more/' => 'pages#learnmore', :as => :learn_more_base
  match '/learn_more/:path' => 'pages#learnmore', :as => :learn_more
  match '/support' => 'pages#support'
  match '/privacy_policy' => 'pages#privacy_policy'
  match '/terms_of_use' => 'pages#terms_of_use'
  match '/why' => 'pages#why'
  match '/requestcenter' => 'pages#requestcenter'
  match '/history' => 'pages#history'
  match '/share' => 'pages#share'
  match '/feedback' => 'pages#feedback'
  match '/signup' => 'users#new'
  match '/settings' => redirect('/settings/account')
  match '/settings/:path' => 'pages#settings', :as => :settings
  match '/download' =>'forms#download', :via => :get
  match '/signin' => 'sessions#new'
  match '/signout' => 'sessions#destroy', :via => :delete
  match '/completerequest/:id' => 'form_requests#completerequest', :as => :completerequest
  match '/completerequestfrompage/:id' => 'form_requests#completerequestfrompage', :as => :completerequestfrompage
  match '/form_requests/edit/:id/:comment' => 'form_requests#edit', :as => :requestcomment
  match '/deleteresponse/:id' => 'form_requests#destroy_response', :as => :deleteresponse
  match '/verify/:id' => 'users#verify', :as => :verify
  match '/deleteforumcomment/:id' => 'forum_comments#delete_forum_comment', :as => :deleteforumcomment
  match '/practicearea' => 'user_practice_areas#update', :via => :post, :as => :practicearea
  match '/follow/:id' => 'form_follows#update', :via => :get, :as => :followform
  match '/unfollow/:id' => 'form_follows#unfollow', :via => :get, :as => :unfollowform
  match '/approveresponse/:id' => 'form_requests#approveresponse', :via => :get, :as => :approveresponse
  match '/share/:id' => 'shared_forms#create', :via => :post, :as => :share

  match ':name' => 'users#show', :as => :usershow










end

app/views/pages/forum_partials/_forum_post_modal.html.erb
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-body">
    <%= form_for(@forumpost) do |f| %>
        <%= f.label :Title %>
        <%= f.text_field :title %>
        <%= f.label :Text %>
        <%= f.text_area :message, :size => "10x5" %>
      <br/>
      <div class="btn-group">
        <%= f.submit "Submit", :class => "btn btn-success", :style => "margin-right:5px;"%>
        <%= button_to "Cancel", "", :class => "btn", :'data-dismiss' => "modal" %>
      </div>
    <% end %>

  </div>

</div>

<a style = "color: green;" data-toggle="modal" href="#myModal" >New Post</a>

app/views/pages/forum_partials/_forum_post_summary.html.erb
<%= link_to f.title, forum_post_path(f) %>
<br/>
<% name = f.user.name.gsub(' ', '_') %>
submitted <%= time_ago_in_words(f.created_at) %> ago by <%= link_to f.user.name, usershow_path(name.downcase)%>