config/routes.rb
Vizibid::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :forms
  resources :comments
  resources :form_requests
  resources :form_ratings
  resources :user_details
  resources :user_notifications
  resources :user_feedbacks, only: [:new, :create]
  resources :inappropriate_documents, only: [:create]
  resources :inappropriate_requests, only: [:create]
  resources :password_resets

  root :to => 'pages#home'

  match 'password_resets/new' => 'password_resets#new', :via => :get
  match '/press' => 'pages#press'
  match '/faq' => 'pages#faq'
  match '/learn_more/' => 'pages#learnmore', :as => :learn_more_base
  match '/learn_more/:path' => 'pages#learnmore', :as => :learn_more
  match '/support' => 'pages#support'
  match '/privacy_policy' => 'pages#privacy_policy'
  match '/terms_of_use' => 'pages#terms_of_use'
  match '/why' => 'pages#why'
  match '/requestcenter' => 'pages#requestcenter'
  match '/history' => 'pages#history'
  match '/share' => 'pages#share'
  match '/feedback' => 'pages#feedback'
  match '/signup' => 'users#new'
  match '/settings' => redirect('/settings/account')
  match '/settings/:path' => 'pages#settings', :as => :settings
  match '/download' =>'forms#download', :via => :get
  match '/signin' => 'sessions#new'
  match '/signout' => 'sessions#destroy', :via => :delete
  match '/completerequest/:id' => 'form_requests#completerequest', :as => :completerequest
  match '/completerequestfrompage/:id' => 'form_requests#completerequestfrompage', :as => :completerequestfrompage
  match '/form_requests/edit/:id/:comment' => 'form_requests#edit', :as => :requestcomment
  match '/deleteresponse/:id' => 'form_requests#destroy_response', :as => :deleteresponse
  match '/verify/:id' => 'users#verify', :as => :verify
  match '/deleteforumcomment/:id' => 'forum_comments#delete_forum_comment', :as => :deleteforumcomment
  match '/practicearea' => 'user_practice_areas#update', :via => :post, :as => :practicearea
  match '/follow/:id' => 'form_follows#update', :via => :get, :as => :followform
  match '/unfollow/:id' => 'form_follows#unfollow', :via => :get, :as => :unfollowform
  match '/approveresponse/:id' => 'form_requests#approveresponse', :via => :get, :as => :approveresponse
  match '/share/:id' => 'shared_forms#create', :via => :post, :as => :share

  match ':name' => 'users#show', :as => :usershow










end

app/views/pages/history_partials/_downloaded_documents_table.html.erb
<div class="downloaded-documents-pane-content">
    <table class="table table-striped">
		<thead>
			<tr>
				<th class="span8">Document</th>
				<th class="span2">Jurisdiction</th>
				<th class="span2">Practice Area</th>
			</tr>
		</thead>
		<% @formdownloads.each do |f| %>
			<tr>
				<td>
					<%= link_to f.form.description, form_path(f.form) %><br/>
					<div style="font-size: 12px;">
						downloaded <%= time_ago_in_words(f.created_at) %> ago
					</div>
				</td>
				<td><%= f.form.jurisdiction %></td>
				<td>
					<% if f.form.practice_area != nil %>
						<%= f.form.practice_area.practice_area_title %>
					<% end %>
				</td>
			</tr>
		<% end %>
	</table>
</div>

app/views/pages/history_partials/_downloaded_tab_pane.html.erb
<div class="tab-content-root">
	<div class="row-fluid">
		<p class="span6" style="text-decoration: underline; margin-top: 5px;">
			Downloaded Documents  (<%= @formdownloads.count %>)
		</p>
		<ul class="nav nav-pills pull-right">
	  	  <li class="recent active"><%= link_to :"Recent", history_path(:tab => "downloaded", :sort => "recent"), :remote => true %></li>
	  	  <li class="alpha"><%= link_to :"Alphabetical", history_path(:tab => "downloaded", :sort => "alpha"), :remote => true %></li>
	  	</ul>
	</div>
	<div class = "downloaded-tab-content">
    	<%= render 'pages/history_partials/downloaded_documents_table' %>
    </div>
</div>

app/views/pages/history_partials/_search_queries_tab_pane.html.erb
<div class="tab-content-root">
	<div class="row-fluid">
		<p class="span6" style="text-decoration: underline; margin-top: 5px;">
			Search Queries
		</p>
		<ul class="nav nav-pills pull-right">
	  	  <li class="recent active"><%= link_to :"Recent", history_path(:tab => "searches", :sort => "recent"), :remote => true %></li>
	  	  <li class="alpha"><%= link_to :"Alphabetical", history_path(:tab => "searches", :sort => "alpha"), :remote => true %></li>
	  	</ul>
	  </div>
  	<div class = "viewed-tab-content">
		<%= render 'pages/history_partials/search_queries_table' %>
	</div>
</div>

app/views/pages/history_partials/_search_queries_table.html.erb
<div class="search-queries-pane-content">
    <table class="table table-striped">
		<thead>
			<tr>
				<th>Search Query</th>
			</tr>
		</thead>
		<% @searchqueries.each do |s| %>
			<tr>
				<td>
					<%= link_to s.query, root_path(:search => s.query) %><br/>
					<div style="font-size: 12px;">
						searched <%= time_ago_in_words(s.created_at) %> ago
					</div>
				</td>
			</tr>
		<% end %>
	</table>
</div>

app/views/pages/history_partials/_uploaded_documents_table.html.erb
<div class="uploaded-documents-pane-content">
    <table class="table table-striped">
		<thead>
			<tr>
				<th class="span8">Document</th>
				<th class="span2">Jurisdiction</th>
				<th class="span2">Practice Area</th>
			</tr>
		</thead>
		<% @uploadedforms.each do |uf| %>
			<tr>
				<td>
					<%= link_to uf.description, form_path(uf) %><br/>
					<div style="font-size: 12px;">
						uploaded <%= time_ago_in_words(uf.created_at) %> ago
					</div>
				</td>
				<td><%= uf.jurisdiction %></td>
				<td>
					<% if uf.practice_area != nil %>
						<%= uf.practice_area.practice_area_title %>
					<% end %>
				</td>
			</tr>
		<% end %>
	</table>
</div>

app/views/pages/history_partials/_uploaded_tab_pane.html.erb
<div class="tab-content-root">
	<div class="row-fluid">
		<p class="span6" style="text-decoration: underline; margin-top: 5px;">
			Uploaded Documents (<%= @uploadedforms.count %>)
		</p>
		<ul class="nav nav-pills pull-right">
	  	  <li class="recent active"><%= link_to :"Recent", history_path(:tab => "uploaded", :sort => "recent"), :remote => true %></li>
	  	  <li class="alpha"><%= link_to :"Alphabetical", history_path(:tab => "uploaded", :sort => "alpha"), :remote => true %></li>
	  	</ul>
	</div>
	<div class = "uploaded-tab-content">
		<%= render 'pages/history_partials/uploaded_documents_table' %>
	</div>
</div>

app/views/pages/history_partials/_viewed_documents_table.html.erb
<div class="viewed-documents-pane-content">
    <table class="table table-striped">
		<thead>
			<tr>
				<th class="span8">Document</th>
				<th class="span2">Jurisdiction</th>
				<th class="span2">Practice Area</th>
			</tr>
		</thead>
		<% @viewedforms.each do |f| %>
			<%if f.form != nil %>
				<tr>
					<td>
						<%= link_to f.form.description, form_path(f.form) %><br/>
						<div style="font-size: 12px;">
							viewed <%= time_ago_in_words(f.created_at) %> ago
						</div>
					</td>
					<td><%= f.form.jurisdiction %></td>
					<td>
						<% if f.form.practice_area != nil %>
							<%= f.form.practice_area.practice_area_title %>
						<% end %>
					</td>
				</tr>
			<% end %>
		<% end %>
	</table>
</div>

app/views/pages/history_partials/_viewed_tab_pane.html.erb
<div class="tab-content-root">
	<div class="row-fluid">
		<p class="span6" style="text-decoration: underline; margin-top: 5px;">
			Viewed Documents (<%= @viewedforms.count %>)
		</p>
		<ul class="nav nav-pills pull-right">
	  	  <li class="recent active"><%= link_to :"Recent", history_path(:tab => "viewed", :sort => "recent"), :remote => true %></li>
	  	  <li class="alpha"><%= link_to :"Alphabetical", history_path(:tab => "viewed", :sort => "alpha"), :remote => true %></li>
	  	</ul>
	  </div>
  	<div class = "viewed-tab-content">
		<%= render 'pages/history_partials/viewed_documents_table' %>
	</div>
</div>